trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: cred.json
  - name: CredFileSdsConfig
    value: sdsconfig.json
  - name: CredFileOidcConfig
    value: oidc.config.json
  - name: CredFileLibrary
    value: product-readiness.sds_angular.cred.json
  - name: CredFileSdsConfigLibrary
    value: product-readiness.sds_angular.sds.json
  - name: CredFileOidcConfigLibrary
    value: product-readiness.sds_angular.oidc.json
  - name: analysisProject
    value: SDS_Angular

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: /e2e/src

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFileSdsConfig)
          fileLibrary: $(CredFileSdsConfigLibrary)
          filePath: /src/app/config

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFileOidcConfig)
          fileLibrary: $(CredFileOidcConfigLibrary)
          filePath: /src/app/config

      - script: npm ci
        displayName: 'Install dependencies'

      - script: npx webdriver-manager update --gecko false --standalone false
        displayName: 'Install chromedriver'

      - script: npm run e2e -- --webdriver-update false
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '*.xml'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)/TestResults'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
