describe('Tests for all home page functions', () => {
  before(() => {
    cy.fixture('cred').then((cred) => {
      cy.loginProcessHeadless(cred.login, cred.pass)
      cy.visit('/');
    })
  })
  
  it('Executes the full sample successfully', () => {
    cy.clickAndAssert('cleanup', '')
    cy.clickAndAssert('createType', '20')
    cy.clickAndAssert('createStream', '20')
    cy.clickAndAssert('writeWaveDataEvents', '20')
    cy.clickAndAssert('retrieveWaveDataEvents', '10 events')
    cy.clickAndAssert('retrieveWaveDataEventsHeaders', '')
    cy.clickAndAssert('updateWaveDataEvents', '20')
    cy.clickAndAssert('replaceWaveDataEvents', '20')
    cy.clickAndAssert('retrieveInterpolatedValues', '')
    cy.clickAndAssert('retrieveFilteredValues', '')
    cy.clickAndAssert('retrieveSampledValues', '')
    cy.clickAndAssert('createPropertyOverrideAndUpdateStream', '20')
    cy.clickAndAssert('createAutoStreamViewTargetType', '20')
    cy.clickAndAssert('createAutoStreamView', '20')
    cy.clickAndAssert('retrieveWaveDataEventsAutoStreamView', '')
    cy.clickAndAssert('createSdsStreamViewPropertiesAndManualType', '20')
    cy.clickAndAssert('retrieveWaveDataEventsManualStreamView', '')
    cy.clickAndAssert('getSdsStreamViewMap', '')
    cy.clickAndAssert('updateStreamType', '')
    cy.clickAndAssert('queryTypes', '')
    cy.clickAndAssert('createTagsAndMetadata', '20')
    cy.clickAndAssert('getAndPrintTags', '')
    cy.clickAndAssert('getAndPrintMetadata', '')
    cy.clickAndAssert('patchMetadata', '20')
    cy.clickAndAssert('getAndPrintMetadata2', '')
    cy.clickAndAssert('getTenantRoles', '20')
    cy.clickAndAssert('shareCommunityStream', '20')
    cy.clickAndAssert('searchCommunity', '20')
    cy.clickAndAssert('getCommunityLast', '20')
    cy.clickAndAssert('deleteAllValues', '20')
    cy.clickAndAssert('secondaryCreate', '20')
    cy.clickAndAssert('secondaryUpdate', '20')
    cy.clickAndAssert('secondaryDelete', '20')
    cy.clickAndAssert('createCompoundTypeandStream', '')
    cy.clickAndAssert('createAndRetrieveCompoundData', '')
    cy.clickAndAssert('cleanup', '')
  })
})
