describe('Tests for all home page functions', () => {
  before(() => {
    cy.fixture('cred').then((cred) => {
      cy.loginProcessHeadless(cred.login, cred.pass)
      cy.visit('/');
    })
  })
  
  it('Executes the full sample successfully', () => {
    cy.clickAndAssert('cleanup', '')
    cy.clickAndAssert('createType', '200')
    cy.clickAndAssert('createStream', '201')
    cy.clickAndAssert('writeWaveDataEvents', '204')
    cy.clickAndAssert('retrieveWaveDataEvents', '10 events')
    cy.clickAndAssert('retrieveWaveDataEventsHeaders', '200')
    cy.clickAndAssert('updateWaveDataEvents', '204')
    cy.clickAndAssert('replaceWaveDataEvents', '204')
    cy.clickAndAssert('retrieveInterpolatedValues', '200')
    cy.clickAndAssert('retrieveFilteredValues', '200')
    cy.clickAndAssert('retrieveSampledValues', '200')
    cy.clickAndAssert('createPropertyOverrideAndUpdateStream', '204')
    cy.clickAndAssert('createAutoStreamViewTargetType', '200')
    cy.clickAndAssert('createAutoStreamView', '200')
    cy.clickAndAssert('retrieveWaveDataEventsAutoStreamView', '5 events')
    cy.clickAndAssert('createSdsStreamViewPropertiesAndManualType', '200')
    cy.clickAndAssert('retrieveWaveDataEventsManualStreamView', '5 events')
    cy.clickAndAssert('getSdsStreamViewMap', 'SdsStreamViewMap')
    cy.clickAndAssert('updateStreamType', '204')
    cy.clickAndAssert('queryTypes', '200')
    cy.clickAndAssert('createTagsAndMetadata', '200')
    cy.clickAndAssert('getAndPrintTags', '')
    cy.clickAndAssert('getAndPrintMetadata', '')
    cy.clickAndAssert('patchMetadata', '200')
    cy.clickAndAssert('getAndPrintMetadata2', '')
    cy.clickAndAssert('getTenantRoles', '200')
    cy.clickAndAssert('shareCommunityStream', '204')
    cy.clickAndAssert('searchCommunity', '200')
    cy.clickAndAssert('getCommunityLast', '200')
    cy.clickAndAssert('deleteAllValues', '204')
    cy.clickAndAssert('secondaryCreate', '201')
    cy.clickAndAssert('secondaryUpdate', '204')
    cy.clickAndAssert('secondaryDelete', '204')
    cy.clickAndAssert('createCompoundTypeandStream', '201')
    cy.clickAndAssert('createAndRetrieveCompoundData', '200')
    cy.clickAndAssert('cleanup', '204')
  })
})
